services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: masterkey
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge
    